jobs:
  - name: docker-image-manifest
    type: manifest
    steps:
      - IN: docker-img
      - IN: docker-img-opts
      - TASK: managed

  - name: deploy-prod
    type: deploy
    steps:
      - IN: docker-image-manifest
      - IN: aws 
      - IN: docker-img-opts 
  
  - name: deploy-pre-prod
    type: deploy
    steps:
      - IN: docker-image-manifest
      - IN: aws2 
      - IN: docker-img-opts 
